# Generated by Django 4.1.3 on 2022-12-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_database',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_num',
            field=models.IntegerField(default=0),
        ),
    ]
