# Generated by Django 4.1.3 on 2022-11-11 00:40

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True ,primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=320)),
                ('location', models.TextField()),
                ('weather', models.TextField()),
                ('news', models.TextField()),
                ('color', models.TextField()),
            ],
        ),
    ]
