# Generated by Django 4.1.3 on 2022-12-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='color',
            field=models.TextField(default="We can't update your color without you updating your color. Give it to us please"),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='location',
            field=models.TextField(default="We don't have your location yet. Give it to us please"),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='news',
            field=models.TextField(default="We can't update your news without your location. Give it to us please"),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='weather',
            field=models.TextField(default="We can't update your weather without your location. Give it to us please"),
        ),
    ]
